// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ssc/chainlet/chainlet_stack_params.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainletStackParams struct {
	Image       string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Version     string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Checksum    string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Enabled     bool   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CcvConsumer bool   `protobuf:"varint,5,opt,name=ccvConsumer,proto3" json:"ccvConsumer,omitempty"`
}

func (m *ChainletStackParams) Reset()         { *m = ChainletStackParams{} }
func (m *ChainletStackParams) String() string { return proto.CompactTextString(m) }
func (*ChainletStackParams) ProtoMessage()    {}
func (*ChainletStackParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_480298f2fc669aaf, []int{0}
}
func (m *ChainletStackParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainletStackParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainletStackParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainletStackParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainletStackParams.Merge(m, src)
}
func (m *ChainletStackParams) XXX_Size() int {
	return m.Size()
}
func (m *ChainletStackParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainletStackParams.DiscardUnknown(m)
}

var xxx_messageInfo_ChainletStackParams proto.InternalMessageInfo

func (m *ChainletStackParams) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ChainletStackParams) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ChainletStackParams) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *ChainletStackParams) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ChainletStackParams) GetCcvConsumer() bool {
	if m != nil {
		return m.CcvConsumer
	}
	return false
}

func init() {
	proto.RegisterType((*ChainletStackParams)(nil), "ssc.chainlet.ChainletStackParams")
}

func init() {
	proto.RegisterFile("ssc/chainlet/chainlet_stack_params.proto", fileDescriptor_480298f2fc669aaf)
}

var fileDescriptor_480298f2fc669aaf = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x2e, 0x4e, 0xd6,
	0x4f, 0xce, 0x48, 0xcc, 0xcc, 0xcb, 0x49, 0x2d, 0x81, 0x33, 0xe2, 0x8b, 0x4b, 0x12, 0x93, 0xb3,
	0xe3, 0x0b, 0x12, 0x8b, 0x12, 0x73, 0x8b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78, 0x8a,
	0x8b, 0x93, 0xf5, 0x60, 0x0a, 0x94, 0xe6, 0x32, 0x72, 0x09, 0x3b, 0x43, 0x39, 0xc1, 0x20, 0xc5,
	0x01, 0x60, 0xb5, 0x42, 0x22, 0x5c, 0xac, 0x99, 0xb9, 0x89, 0xe9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x04, 0x17, 0x7b, 0x59, 0x6a, 0x51, 0x71, 0x66, 0x7e, 0x9e,
	0x04, 0x13, 0x58, 0x1c, 0xc6, 0x15, 0x92, 0xe2, 0xe2, 0x48, 0xce, 0x48, 0x4d, 0xce, 0x2e, 0x2e,
	0xcd, 0x95, 0x60, 0x06, 0x4b, 0xc1, 0xf9, 0x20, 0x5d, 0xa9, 0x79, 0x89, 0x49, 0x39, 0xa9, 0x29,
	0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x90, 0x02, 0x17, 0x77, 0x72, 0x72, 0x99,
	0x73, 0x7e, 0x5e, 0x71, 0x69, 0x6e, 0x6a, 0x91, 0x04, 0x2b, 0x58, 0x16, 0x59, 0xc8, 0xc9, 0xf1,
	0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e,
	0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0xd4, 0xd3, 0x33, 0x4b, 0x32, 0x4a,
	0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x8b, 0x13, 0xd3, 0x13, 0x2b, 0x2a, 0xab, 0xf4, 0x41, 0x81,
	0x50, 0x81, 0x08, 0x86, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24, 0x36, 0xb0, 0xbf, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xfc, 0xe6, 0x3b, 0x1a, 0x23, 0x01, 0x00, 0x00,
}

func (m *ChainletStackParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainletStackParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainletStackParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CcvConsumer {
		i--
		if m.CcvConsumer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Checksum) > 0 {
		i -= len(m.Checksum)
		copy(dAtA[i:], m.Checksum)
		i = encodeVarintChainletStackParams(dAtA, i, uint64(len(m.Checksum)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintChainletStackParams(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintChainletStackParams(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChainletStackParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovChainletStackParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainletStackParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovChainletStackParams(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovChainletStackParams(uint64(l))
	}
	l = len(m.Checksum)
	if l > 0 {
		n += 1 + l + sovChainletStackParams(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	if m.CcvConsumer {
		n += 2
	}
	return n
}

func sovChainletStackParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChainletStackParams(x uint64) (n int) {
	return sovChainletStackParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainletStackParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainletStackParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainletStackParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainletStackParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Checksum = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CcvConsumer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CcvConsumer = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipChainletStackParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainletStackParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChainletStackParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChainletStackParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainletStackParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChainletStackParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChainletStackParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChainletStackParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChainletStackParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChainletStackParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChainletStackParams = fmt.Errorf("proto: unexpected end of group")
)
