// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ssc/chainlet/chainlet_params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainletParams struct {
	GasLimit uint64 `protobuf:"varint,1,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	// Config.toml params - can be set and modified via a chainlet update
	CreateEmptyBlocks bool `protobuf:"varint,2,opt,name=createEmptyBlocks,proto3" json:"createEmptyBlocks,omitempty"`
	// Enables deployment access control
	DacEnable bool `protobuf:"varint,3,opt,name=dacEnable,proto3" json:"dacEnable,omitempty"`
	// Genesis accounts and balances
	GenAcctBalances GenesisAccountBalances `protobuf:"bytes,4,opt,name=genAcctBalances,proto3" json:"genAcctBalances"`
	// Constant EIP-1559 base fee
	FixedBaseFee string `protobuf:"bytes,5,opt,name=fixedBaseFee,proto3" json:"fixedBaseFee,omitempty"`
	FeeAccount   string `protobuf:"bytes,6,opt,name=feeAccount,proto3" json:"feeAccount,omitempty"`
}

func (m *ChainletParams) Reset()         { *m = ChainletParams{} }
func (m *ChainletParams) String() string { return proto.CompactTextString(m) }
func (*ChainletParams) ProtoMessage()    {}
func (*ChainletParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_335dcc096f99ee7a, []int{0}
}
func (m *ChainletParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainletParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainletParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainletParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainletParams.Merge(m, src)
}
func (m *ChainletParams) XXX_Size() int {
	return m.Size()
}
func (m *ChainletParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainletParams.DiscardUnknown(m)
}

var xxx_messageInfo_ChainletParams proto.InternalMessageInfo

func (m *ChainletParams) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *ChainletParams) GetCreateEmptyBlocks() bool {
	if m != nil {
		return m.CreateEmptyBlocks
	}
	return false
}

func (m *ChainletParams) GetDacEnable() bool {
	if m != nil {
		return m.DacEnable
	}
	return false
}

func (m *ChainletParams) GetGenAcctBalances() GenesisAccountBalances {
	if m != nil {
		return m.GenAcctBalances
	}
	return GenesisAccountBalances{}
}

func (m *ChainletParams) GetFixedBaseFee() string {
	if m != nil {
		return m.FixedBaseFee
	}
	return ""
}

func (m *ChainletParams) GetFeeAccount() string {
	if m != nil {
		return m.FeeAccount
	}
	return ""
}

func init() {
	proto.RegisterType((*ChainletParams)(nil), "ssc.chainlet.ChainletParams")
}

func init() {
	proto.RegisterFile("ssc/chainlet/chainlet_params.proto", fileDescriptor_335dcc096f99ee7a)
}

var fileDescriptor_335dcc096f99ee7a = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4a, 0xeb, 0x40,
	0x18, 0xc5, 0x33, 0xbd, 0xbd, 0xa5, 0x9d, 0x5b, 0xae, 0x38, 0xb8, 0x08, 0x45, 0xc6, 0x50, 0x04,
	0x03, 0x4a, 0x02, 0xfa, 0x04, 0x8d, 0x54, 0x37, 0x2e, 0x24, 0xb8, 0x72, 0x53, 0xbe, 0x4c, 0xbf,
	0x4e, 0x83, 0x49, 0x26, 0x74, 0xa6, 0xd0, 0xfa, 0x14, 0xe2, 0x53, 0x75, 0xd9, 0xa5, 0x2b, 0x91,
	0xf6, 0x45, 0xa4, 0x69, 0xfa, 0x4f, 0x77, 0x5f, 0xce, 0xf9, 0x71, 0x32, 0xe7, 0xd0, 0xb6, 0xd6,
	0xc2, 0x17, 0x43, 0x88, 0xb3, 0x04, 0xcd, 0xf6, 0xe8, 0xe5, 0x30, 0x82, 0x54, 0x7b, 0xf9, 0x48,
	0x19, 0xc5, 0x9a, 0x5a, 0x0b, 0x6f, 0x63, 0xb5, 0x4e, 0xa4, 0x92, 0xaa, 0x30, 0xfc, 0xd5, 0xb5,
	0x66, 0x5a, 0x97, 0x07, 0x39, 0x12, 0x33, 0xd4, 0xb1, 0xee, 0x81, 0x10, 0x6a, 0x9c, 0x99, 0x5e,
	0x04, 0x09, 0x64, 0x02, 0xcb, 0xc0, 0xf6, 0x7b, 0x85, 0xfe, 0xbf, 0x2d, 0xd9, 0xc7, 0xe2, 0x4f,
	0xac, 0x45, 0xeb, 0x12, 0xf4, 0x43, 0x9c, 0xc6, 0xc6, 0x26, 0x0e, 0x71, 0xab, 0xe1, 0xf6, 0x9b,
	0x5d, 0xd1, 0x63, 0x31, 0x42, 0x30, 0xd8, 0x4d, 0x73, 0x33, 0x0d, 0x12, 0x25, 0x5e, 0xb4, 0x5d,
	0x71, 0x88, 0x5b, 0x0f, 0x7f, 0x1b, 0xec, 0x94, 0x36, 0xfa, 0x20, 0xba, 0x19, 0x44, 0x09, 0xda,
	0x7f, 0x0a, 0x6a, 0x27, 0xb0, 0x27, 0x7a, 0x24, 0x31, 0xeb, 0x08, 0x61, 0x82, 0xf2, 0x4d, 0x76,
	0xd5, 0x21, 0xee, 0xbf, 0xeb, 0x73, 0x6f, 0xbf, 0xa5, 0x77, 0xbf, 0x6e, 0xd0, 0x59, 0x17, 0xd8,
	0xb0, 0x41, 0x75, 0xf6, 0x79, 0x66, 0x85, 0x3f, 0x23, 0x58, 0x9b, 0x36, 0x07, 0xf1, 0x04, 0xfb,
	0x01, 0x68, 0xbc, 0x43, 0xb4, 0xff, 0x3a, 0xc4, 0x6d, 0x84, 0x07, 0x1a, 0xe3, 0x94, 0x0e, 0x10,
	0xcb, 0x40, 0xbb, 0x56, 0x10, 0x7b, 0x4a, 0xd0, 0x99, 0x2d, 0x38, 0x99, 0x2f, 0x38, 0xf9, 0x5a,
	0x70, 0xf2, 0xb6, 0xe4, 0xd6, 0x7c, 0xc9, 0xad, 0x8f, 0x25, 0xb7, 0x9e, 0x2f, 0x64, 0x6c, 0x86,
	0xe3, 0xc8, 0x13, 0x2a, 0xf5, 0x35, 0x48, 0x98, 0x4c, 0x5f, 0xfd, 0xd5, 0xdc, 0x93, 0xdd, 0xe0,
	0x66, 0x9a, 0xa3, 0x8e, 0x6a, 0xc5, 0xbc, 0x37, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x5c,
	0xa7, 0x58, 0xd5, 0x01, 0x00, 0x00,
}

func (m *ChainletParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainletParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainletParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeAccount) > 0 {
		i -= len(m.FeeAccount)
		copy(dAtA[i:], m.FeeAccount)
		i = encodeVarintChainletParams(dAtA, i, uint64(len(m.FeeAccount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.FixedBaseFee) > 0 {
		i -= len(m.FixedBaseFee)
		copy(dAtA[i:], m.FixedBaseFee)
		i = encodeVarintChainletParams(dAtA, i, uint64(len(m.FixedBaseFee)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.GenAcctBalances.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintChainletParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.DacEnable {
		i--
		if m.DacEnable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.CreateEmptyBlocks {
		i--
		if m.CreateEmptyBlocks {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.GasLimit != 0 {
		i = encodeVarintChainletParams(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintChainletParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovChainletParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainletParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GasLimit != 0 {
		n += 1 + sovChainletParams(uint64(m.GasLimit))
	}
	if m.CreateEmptyBlocks {
		n += 2
	}
	if m.DacEnable {
		n += 2
	}
	l = m.GenAcctBalances.Size()
	n += 1 + l + sovChainletParams(uint64(l))
	l = len(m.FixedBaseFee)
	if l > 0 {
		n += 1 + l + sovChainletParams(uint64(l))
	}
	l = len(m.FeeAccount)
	if l > 0 {
		n += 1 + l + sovChainletParams(uint64(l))
	}
	return n
}

func sovChainletParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChainletParams(x uint64) (n int) {
	return sovChainletParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainletParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainletParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainletParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainletParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateEmptyBlocks", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CreateEmptyBlocks = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DacEnable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DacEnable = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenAcctBalances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainletParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainletParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GenAcctBalances.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedBaseFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FixedBaseFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainletParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainletParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChainletParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChainletParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainletParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChainletParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChainletParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChainletParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChainletParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChainletParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChainletParams = fmt.Errorf("proto: unexpected end of group")
)
