// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ssc/chainlet/chainlet_stack.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainletStack struct {
	Creator     string                `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	DisplayName string                `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	Description string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Versions    []ChainletStackParams `protobuf:"bytes,4,rep,name=versions,proto3" json:"versions"`
	Fees        ChainletStackFees     `protobuf:"bytes,5,opt,name=fees,proto3" json:"fees"`
	CcvConsumer bool                  `protobuf:"varint,6,opt,name=ccvConsumer,proto3" json:"ccvConsumer,omitempty"`
}

func (m *ChainletStack) Reset()         { *m = ChainletStack{} }
func (m *ChainletStack) String() string { return proto.CompactTextString(m) }
func (*ChainletStack) ProtoMessage()    {}
func (*ChainletStack) Descriptor() ([]byte, []int) {
	return fileDescriptor_f413fb807a778764, []int{0}
}
func (m *ChainletStack) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainletStack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainletStack.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainletStack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainletStack.Merge(m, src)
}
func (m *ChainletStack) XXX_Size() int {
	return m.Size()
}
func (m *ChainletStack) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainletStack.DiscardUnknown(m)
}

var xxx_messageInfo_ChainletStack proto.InternalMessageInfo

func (m *ChainletStack) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ChainletStack) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ChainletStack) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ChainletStack) GetVersions() []ChainletStackParams {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *ChainletStack) GetFees() ChainletStackFees {
	if m != nil {
		return m.Fees
	}
	return ChainletStackFees{}
}

func (m *ChainletStack) GetCcvConsumer() bool {
	if m != nil {
		return m.CcvConsumer
	}
	return false
}

type ChainletStackFees struct {
	EpochFee    string `protobuf:"bytes,1,opt,name=epochFee,proto3" json:"epochFee,omitempty"`
	EpochLength string `protobuf:"bytes,2,opt,name=epochLength,proto3" json:"epochLength,omitempty"`
	SetupFee    string `protobuf:"bytes,3,opt,name=setupFee,proto3" json:"setupFee,omitempty"`
}

func (m *ChainletStackFees) Reset()         { *m = ChainletStackFees{} }
func (m *ChainletStackFees) String() string { return proto.CompactTextString(m) }
func (*ChainletStackFees) ProtoMessage()    {}
func (*ChainletStackFees) Descriptor() ([]byte, []int) {
	return fileDescriptor_f413fb807a778764, []int{1}
}
func (m *ChainletStackFees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainletStackFees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainletStackFees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainletStackFees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainletStackFees.Merge(m, src)
}
func (m *ChainletStackFees) XXX_Size() int {
	return m.Size()
}
func (m *ChainletStackFees) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainletStackFees.DiscardUnknown(m)
}

var xxx_messageInfo_ChainletStackFees proto.InternalMessageInfo

func (m *ChainletStackFees) GetEpochFee() string {
	if m != nil {
		return m.EpochFee
	}
	return ""
}

func (m *ChainletStackFees) GetEpochLength() string {
	if m != nil {
		return m.EpochLength
	}
	return ""
}

func (m *ChainletStackFees) GetSetupFee() string {
	if m != nil {
		return m.SetupFee
	}
	return ""
}

func init() {
	proto.RegisterType((*ChainletStack)(nil), "ssc.chainlet.ChainletStack")
	proto.RegisterType((*ChainletStackFees)(nil), "ssc.chainlet.ChainletStackFees")
}

func init() { proto.RegisterFile("ssc/chainlet/chainlet_stack.proto", fileDescriptor_f413fb807a778764) }

var fileDescriptor_f413fb807a778764 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x3f, 0x4f, 0xc2, 0x40,
	0x14, 0x6f, 0x01, 0x11, 0x0f, 0x1d, 0x6c, 0x1c, 0x1a, 0x86, 0x52, 0x58, 0xec, 0xd4, 0x26, 0x38,
	0x39, 0x0a, 0x09, 0x93, 0x31, 0x06, 0x37, 0x17, 0x72, 0x9c, 0xcf, 0xb6, 0x91, 0xf6, 0x9a, 0x7b,
	0x07, 0x01, 0xbf, 0x84, 0x7e, 0x2c, 0x46, 0x46, 0x27, 0x63, 0xe0, 0x8b, 0x98, 0x3b, 0x68, 0xa9,
	0x31, 0x61, 0x7b, 0xef, 0xf7, 0x2f, 0xef, 0x0f, 0xe9, 0x20, 0xb2, 0x80, 0x45, 0x34, 0x4e, 0xa7,
	0x20, 0x8b, 0x62, 0x8c, 0x92, 0xb2, 0x37, 0x3f, 0x13, 0x5c, 0x72, 0xeb, 0x1c, 0x91, 0xf9, 0x39,
	0xd3, 0xba, 0x0a, 0x79, 0xc8, 0x35, 0x11, 0xa8, 0x6a, 0xa7, 0x69, 0x79, 0x47, 0x62, 0xc6, 0x19,
	0x15, 0x34, 0xc1, 0x9d, 0xb2, 0xfb, 0x51, 0x21, 0x17, 0x83, 0x3d, 0xff, 0xa4, 0x68, 0xcb, 0x26,
	0xa7, 0x4c, 0x00, 0x95, 0x5c, 0xd8, 0xa6, 0x6b, 0x7a, 0x67, 0xa3, 0xbc, 0xb5, 0x5c, 0xd2, 0x7c,
	0x89, 0x31, 0x9b, 0xd2, 0xe5, 0x03, 0x4d, 0xc0, 0xae, 0x68, 0xb6, 0x0c, 0x69, 0x05, 0x20, 0x13,
	0x71, 0x26, 0x63, 0x9e, 0xda, 0xd5, 0xbd, 0xe2, 0x00, 0x59, 0x03, 0xd2, 0x98, 0x83, 0xc0, 0x98,
	0xa7, 0x68, 0xd7, 0xdc, 0xaa, 0xd7, 0xec, 0x75, 0xfc, 0xf2, 0x42, 0xfe, 0x9f, 0x61, 0x1e, 0xf5,
	0xa8, 0xfd, 0xda, 0xea, 0xbb, 0x6d, 0x8c, 0x0a, 0xa3, 0x75, 0x4b, 0x6a, 0xaf, 0x00, 0x68, 0x9f,
	0xb8, 0xa6, 0xd7, 0xec, 0xb5, 0x8f, 0x04, 0x0c, 0x01, 0x72, 0xbb, 0xb6, 0xa8, 0x09, 0x19, 0x9b,
	0x0f, 0x78, 0x8a, 0xb3, 0x04, 0x84, 0x5d, 0x77, 0x4d, 0xaf, 0x31, 0x2a, 0x43, 0xdd, 0x84, 0x5c,
	0xfe, 0x8b, 0xb0, 0x5a, 0xa4, 0x01, 0x19, 0x67, 0xd1, 0x10, 0x60, 0x7f, 0x95, 0xa2, 0x57, 0x91,
	0xba, 0xbe, 0x87, 0x34, 0x94, 0x51, 0x7e, 0x96, 0x12, 0xa4, 0xdc, 0x08, 0x72, 0x96, 0x29, 0xf7,
	0xee, 0x26, 0x45, 0xdf, 0xbf, 0x5b, 0x6d, 0x1c, 0x73, 0xbd, 0x71, 0xcc, 0x9f, 0x8d, 0x63, 0x7e,
	0x6e, 0x1d, 0x63, 0xbd, 0x75, 0x8c, 0xaf, 0xad, 0x63, 0x3c, 0x5f, 0x87, 0xb1, 0x8c, 0x66, 0x13,
	0x9f, 0xf1, 0x24, 0x40, 0x1a, 0xd2, 0xc5, 0xf2, 0x3d, 0x50, 0x7f, 0x5d, 0x1c, 0x3e, 0x2b, 0x97,
	0x19, 0xe0, 0xa4, 0xae, 0x5f, 0x79, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x48, 0xc6, 0x23,
	0x3d, 0x02, 0x00, 0x00,
}

func (m *ChainletStack) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainletStack) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainletStack) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CcvConsumer {
		i--
		if m.CcvConsumer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.Fees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintChainletStack(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Versions) > 0 {
		for iNdEx := len(m.Versions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Versions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintChainletStack(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintChainletStack(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintChainletStack(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintChainletStack(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChainletStackFees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainletStackFees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainletStackFees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SetupFee) > 0 {
		i -= len(m.SetupFee)
		copy(dAtA[i:], m.SetupFee)
		i = encodeVarintChainletStack(dAtA, i, uint64(len(m.SetupFee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EpochLength) > 0 {
		i -= len(m.EpochLength)
		copy(dAtA[i:], m.EpochLength)
		i = encodeVarintChainletStack(dAtA, i, uint64(len(m.EpochLength)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.EpochFee) > 0 {
		i -= len(m.EpochFee)
		copy(dAtA[i:], m.EpochFee)
		i = encodeVarintChainletStack(dAtA, i, uint64(len(m.EpochFee)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChainletStack(dAtA []byte, offset int, v uint64) int {
	offset -= sovChainletStack(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainletStack) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovChainletStack(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovChainletStack(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovChainletStack(uint64(l))
	}
	if len(m.Versions) > 0 {
		for _, e := range m.Versions {
			l = e.Size()
			n += 1 + l + sovChainletStack(uint64(l))
		}
	}
	l = m.Fees.Size()
	n += 1 + l + sovChainletStack(uint64(l))
	if m.CcvConsumer {
		n += 2
	}
	return n
}

func (m *ChainletStackFees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EpochFee)
	if l > 0 {
		n += 1 + l + sovChainletStack(uint64(l))
	}
	l = len(m.EpochLength)
	if l > 0 {
		n += 1 + l + sovChainletStack(uint64(l))
	}
	l = len(m.SetupFee)
	if l > 0 {
		n += 1 + l + sovChainletStack(uint64(l))
	}
	return n
}

func sovChainletStack(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChainletStack(x uint64) (n int) {
	return sovChainletStack(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainletStack) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainletStack
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainletStack: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainletStack: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Versions = append(m.Versions, ChainletStackParams{})
			if err := m.Versions[len(m.Versions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CcvConsumer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CcvConsumer = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipChainletStack(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainletStack
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainletStackFees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainletStack
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainletStackFees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainletStackFees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLength", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochLength = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetupFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainletStack
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainletStack
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SetupFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainletStack(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainletStack
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChainletStack(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChainletStack
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainletStack
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChainletStack
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChainletStack
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChainletStack
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChainletStack        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChainletStack          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChainletStack = fmt.Errorf("proto: unexpected end of group")
)
