// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ssc/chainlet/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListChainletStackRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListChainletStackRequest) Reset()         { *m = QueryListChainletStackRequest{} }
func (m *QueryListChainletStackRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListChainletStackRequest) ProtoMessage()    {}
func (*QueryListChainletStackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{2}
}
func (m *QueryListChainletStackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListChainletStackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListChainletStackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListChainletStackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListChainletStackRequest.Merge(m, src)
}
func (m *QueryListChainletStackRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListChainletStackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListChainletStackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListChainletStackRequest proto.InternalMessageInfo

func (m *QueryListChainletStackRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListChainletStackResponse struct {
	ChainletStacks []*ChainletStack    `protobuf:"bytes,1,rep,name=ChainletStacks,proto3" json:"ChainletStacks,omitempty"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListChainletStackResponse) Reset()         { *m = QueryListChainletStackResponse{} }
func (m *QueryListChainletStackResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListChainletStackResponse) ProtoMessage()    {}
func (*QueryListChainletStackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{3}
}
func (m *QueryListChainletStackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListChainletStackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListChainletStackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListChainletStackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListChainletStackResponse.Merge(m, src)
}
func (m *QueryListChainletStackResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListChainletStackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListChainletStackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListChainletStackResponse proto.InternalMessageInfo

func (m *QueryListChainletStackResponse) GetChainletStacks() []*ChainletStack {
	if m != nil {
		return m.ChainletStacks
	}
	return nil
}

func (m *QueryListChainletStackResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetChainletStackRequest struct {
	DisplayName string `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
}

func (m *QueryGetChainletStackRequest) Reset()         { *m = QueryGetChainletStackRequest{} }
func (m *QueryGetChainletStackRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetChainletStackRequest) ProtoMessage()    {}
func (*QueryGetChainletStackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{4}
}
func (m *QueryGetChainletStackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetChainletStackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetChainletStackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetChainletStackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetChainletStackRequest.Merge(m, src)
}
func (m *QueryGetChainletStackRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetChainletStackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetChainletStackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetChainletStackRequest proto.InternalMessageInfo

func (m *QueryGetChainletStackRequest) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type QueryGetChainletStackResponse struct {
	ChainletStack ChainletStack `protobuf:"bytes,1,opt,name=ChainletStack,proto3" json:"ChainletStack"`
}

func (m *QueryGetChainletStackResponse) Reset()         { *m = QueryGetChainletStackResponse{} }
func (m *QueryGetChainletStackResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetChainletStackResponse) ProtoMessage()    {}
func (*QueryGetChainletStackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{5}
}
func (m *QueryGetChainletStackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetChainletStackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetChainletStackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetChainletStackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetChainletStackResponse.Merge(m, src)
}
func (m *QueryGetChainletStackResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetChainletStackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetChainletStackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetChainletStackResponse proto.InternalMessageInfo

func (m *QueryGetChainletStackResponse) GetChainletStack() ChainletStack {
	if m != nil {
		return m.ChainletStack
	}
	return ChainletStack{}
}

type QueryListChainletsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListChainletsRequest) Reset()         { *m = QueryListChainletsRequest{} }
func (m *QueryListChainletsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListChainletsRequest) ProtoMessage()    {}
func (*QueryListChainletsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{6}
}
func (m *QueryListChainletsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListChainletsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListChainletsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListChainletsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListChainletsRequest.Merge(m, src)
}
func (m *QueryListChainletsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListChainletsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListChainletsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListChainletsRequest proto.InternalMessageInfo

func (m *QueryListChainletsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListChainletsResponse struct {
	Chainlets  []*Chainlet         `protobuf:"bytes,1,rep,name=Chainlets,proto3" json:"Chainlets,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListChainletsResponse) Reset()         { *m = QueryListChainletsResponse{} }
func (m *QueryListChainletsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListChainletsResponse) ProtoMessage()    {}
func (*QueryListChainletsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{7}
}
func (m *QueryListChainletsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListChainletsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListChainletsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListChainletsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListChainletsResponse.Merge(m, src)
}
func (m *QueryListChainletsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListChainletsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListChainletsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListChainletsResponse proto.InternalMessageInfo

func (m *QueryListChainletsResponse) GetChainlets() []*Chainlet {
	if m != nil {
		return m.Chainlets
	}
	return nil
}

func (m *QueryListChainletsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetChainletRequest struct {
	ChainId string `protobuf:"bytes,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (m *QueryGetChainletRequest) Reset()         { *m = QueryGetChainletRequest{} }
func (m *QueryGetChainletRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetChainletRequest) ProtoMessage()    {}
func (*QueryGetChainletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{8}
}
func (m *QueryGetChainletRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetChainletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetChainletRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetChainletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetChainletRequest.Merge(m, src)
}
func (m *QueryGetChainletRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetChainletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetChainletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetChainletRequest proto.InternalMessageInfo

func (m *QueryGetChainletRequest) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type QueryGetChainletResponse struct {
	Chainlet Chainlet `protobuf:"bytes,1,opt,name=Chainlet,proto3" json:"Chainlet"`
}

func (m *QueryGetChainletResponse) Reset()         { *m = QueryGetChainletResponse{} }
func (m *QueryGetChainletResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetChainletResponse) ProtoMessage()    {}
func (*QueryGetChainletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79bbab29ed6da853, []int{9}
}
func (m *QueryGetChainletResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetChainletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetChainletResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetChainletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetChainletResponse.Merge(m, src)
}
func (m *QueryGetChainletResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetChainletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetChainletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetChainletResponse proto.InternalMessageInfo

func (m *QueryGetChainletResponse) GetChainlet() Chainlet {
	if m != nil {
		return m.Chainlet
	}
	return Chainlet{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ssc.chainlet.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ssc.chainlet.QueryParamsResponse")
	proto.RegisterType((*QueryListChainletStackRequest)(nil), "ssc.chainlet.QueryListChainletStackRequest")
	proto.RegisterType((*QueryListChainletStackResponse)(nil), "ssc.chainlet.QueryListChainletStackResponse")
	proto.RegisterType((*QueryGetChainletStackRequest)(nil), "ssc.chainlet.QueryGetChainletStackRequest")
	proto.RegisterType((*QueryGetChainletStackResponse)(nil), "ssc.chainlet.QueryGetChainletStackResponse")
	proto.RegisterType((*QueryListChainletsRequest)(nil), "ssc.chainlet.QueryListChainletsRequest")
	proto.RegisterType((*QueryListChainletsResponse)(nil), "ssc.chainlet.QueryListChainletsResponse")
	proto.RegisterType((*QueryGetChainletRequest)(nil), "ssc.chainlet.QueryGetChainletRequest")
	proto.RegisterType((*QueryGetChainletResponse)(nil), "ssc.chainlet.QueryGetChainletResponse")
}

func init() { proto.RegisterFile("ssc/chainlet/query.proto", fileDescriptor_79bbab29ed6da853) }

var fileDescriptor_79bbab29ed6da853 = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0xbb, 0x28, 0x28, 0xaf, 0x62, 0x74, 0x6c, 0xb0, 0x2c, 0x75, 0x85, 0x15, 0x01, 0x81,
	0xec, 0x48, 0x31, 0xc6, 0xa3, 0x42, 0x22, 0x21, 0x31, 0x06, 0xab, 0x27, 0x2f, 0x64, 0xba, 0x4c,
	0x96, 0x0d, 0xed, 0xce, 0xc2, 0x2c, 0x86, 0x4a, 0xb8, 0x78, 0x32, 0x9e, 0x4c, 0x3c, 0x19, 0x8f,
	0xde, 0xfd, 0x1c, 0x9c, 0x0c, 0x89, 0x17, 0x4f, 0xc6, 0x50, 0x3f, 0x88, 0xe9, 0xec, 0xdb, 0xb6,
	0xd3, 0x6e, 0x5b, 0x0e, 0xdc, 0xb6, 0xf3, 0xfe, 0xef, 0xcd, 0xef, 0xfd, 0x5f, 0xdf, 0x2e, 0xe4,
	0xa5, 0x74, 0xa9, 0xbb, 0xc3, 0xfc, 0xa0, 0xc2, 0x23, 0xba, 0x77, 0xc0, 0xf7, 0x6b, 0x4e, 0xb8,
	0x2f, 0x22, 0x41, 0xae, 0x49, 0xe9, 0x3a, 0x49, 0xc4, 0xcc, 0x79, 0xc2, 0x13, 0x2a, 0x40, 0x1b,
	0x4f, 0xb1, 0xc6, 0x2c, 0x78, 0x42, 0x78, 0x15, 0x4e, 0x59, 0xe8, 0x53, 0x16, 0x04, 0x22, 0x62,
	0x91, 0x2f, 0x02, 0x89, 0xd1, 0x05, 0x57, 0xc8, 0xaa, 0x90, 0xb4, 0xcc, 0x24, 0x8f, 0x4b, 0xd3,
	0x77, 0xcb, 0x65, 0x1e, 0xb1, 0x65, 0x1a, 0x32, 0xcf, 0x0f, 0x94, 0x18, 0xb5, 0x13, 0x1a, 0x47,
	0xc8, 0xf6, 0x59, 0x35, 0x29, 0x33, 0xad, 0x85, 0x92, 0x87, 0x2d, 0x19, 0x31, 0x77, 0x17, 0x25,
	0x93, 0xa9, 0x92, 0x38, 0x68, 0xe7, 0x80, 0xbc, 0x6a, 0x5c, 0xbe, 0xa9, 0x8a, 0x96, 0xf8, 0xde,
	0x01, 0x97, 0x91, 0xbd, 0x01, 0xb7, 0xb4, 0x53, 0x19, 0x8a, 0x40, 0x72, 0x52, 0x84, 0x91, 0xf8,
	0xf2, 0xbc, 0x31, 0x65, 0xcc, 0x67, 0x8b, 0x39, 0xa7, 0xdd, 0x06, 0x27, 0x56, 0xaf, 0x5e, 0x3e,
	0xf9, 0x73, 0x37, 0x53, 0x42, 0xa5, 0xed, 0xc1, 0x1d, 0x55, 0xea, 0x85, 0x2f, 0xa3, 0x35, 0x54,
	0xbe, 0x6e, 0xd0, 0xe1, 0x5d, 0xe4, 0x39, 0x40, 0xab, 0x61, 0x2c, 0x3c, 0xeb, 0xc4, 0xee, 0x38,
	0x0d, 0x77, 0x9c, 0xd8, 0x78, 0x74, 0xc7, 0xd9, 0x64, 0x1e, 0xc7, 0xdc, 0x52, 0x5b, 0xa6, 0xfd,
	0xc3, 0x00, 0xab, 0xd7, 0x4d, 0xc8, 0xbf, 0x06, 0xd7, 0xb5, 0x40, 0xa3, 0x8f, 0x4b, 0xf3, 0xd9,
	0xe2, 0xa4, 0xde, 0x87, 0x9e, 0xdc, 0x91, 0x42, 0xd6, 0x35, 0xde, 0x21, 0xc5, 0x3b, 0x37, 0x90,
	0x37, 0x26, 0xd0, 0x80, 0x9f, 0x42, 0x41, 0xf1, 0xae, 0xf3, 0x74, 0x63, 0xa6, 0x20, 0xbb, 0xed,
	0xcb, 0xb0, 0xc2, 0x6a, 0x2f, 0x59, 0x95, 0x2b, 0x67, 0x46, 0x4b, 0xed, 0x47, 0xf6, 0x0e, 0x7a,
	0xdb, 0x5d, 0x01, 0x1b, 0x5e, 0x87, 0x31, 0x2d, 0x80, 0xf6, 0xf6, 0xeb, 0x17, 0xc7, 0xa7, 0xe7,
	0xd9, 0x2e, 0x4c, 0x74, 0x79, 0x2b, 0x2f, 0x7a, 0x82, 0xdf, 0x0c, 0x30, 0xd3, 0x6e, 0xc1, 0x66,
	0x1e, 0xc1, 0x68, 0xf3, 0x10, 0x07, 0x37, 0x9e, 0xde, 0x48, 0xa9, 0x25, 0xbc, 0xb8, 0x71, 0xad,
	0xc0, 0xed, 0x4e, 0xb3, 0x13, 0x03, 0xf2, 0x70, 0x45, 0x31, 0x6c, 0x6c, 0xe3, 0x94, 0x92, 0x9f,
	0xf6, 0x1b, 0xc8, 0x77, 0x27, 0x61, 0x3f, 0x4f, 0xe0, 0x6a, 0x72, 0x86, 0xa6, 0xf5, 0x68, 0x07,
	0x47, 0xd2, 0x54, 0x17, 0x7f, 0x0e, 0xc3, 0xb0, 0x2a, 0x4b, 0x76, 0x61, 0x24, 0xde, 0x3a, 0x32,
	0xa5, 0xe7, 0x76, 0x2f, 0xb5, 0x39, 0xdd, 0x47, 0x11, 0x23, 0xd9, 0x85, 0x0f, 0xbf, 0xfe, 0x7d,
	0x19, 0x1a, 0x27, 0x39, 0x9a, 0xf2, 0xc6, 0x21, 0x5f, 0x0d, 0xb8, 0xd9, 0xb5, 0x5c, 0x64, 0x31,
	0xa5, 0x6c, 0xaf, 0x65, 0x37, 0x97, 0xce, 0x27, 0x46, 0x9c, 0x07, 0x0a, 0xe7, 0x1e, 0x99, 0xd6,
	0x71, 0x2a, 0xbe, 0x8c, 0xb6, 0xf4, 0x57, 0x1d, 0xf9, 0x6e, 0xc0, 0x8d, 0xce, 0x35, 0x20, 0x0b,
	0x29, 0xb7, 0xf5, 0xd8, 0x36, 0x73, 0xf1, 0x5c, 0x5a, 0x04, 0x7b, 0xac, 0xc0, 0x1e, 0x12, 0x47,
	0x07, 0xf3, 0x78, 0x27, 0x17, 0x3d, 0x6a, 0xdb, 0xd7, 0x63, 0xf2, 0xd1, 0x80, 0x31, 0xed, 0xcf,
	0x4d, 0xe6, 0x06, 0x18, 0xd2, 0x9c, 0xde, 0xfc, 0x60, 0x21, 0xc2, 0xcd, 0x28, 0x38, 0x8b, 0x14,
	0xfa, 0xb8, 0x26, 0xc9, 0x27, 0x03, 0xb2, 0x6d, 0xfd, 0x91, 0xfb, 0xfd, 0xfb, 0x4f, 0x30, 0x66,
	0x07, 0xc9, 0x10, 0x62, 0x49, 0x41, 0xcc, 0x92, 0x99, 0xde, 0x0e, 0xd1, 0x23, 0xdc, 0x92, 0xe3,
	0xd5, 0x67, 0x27, 0x67, 0x96, 0x71, 0x7a, 0x66, 0x19, 0x7f, 0xcf, 0x2c, 0xe3, 0x73, 0xdd, 0xca,
	0x9c, 0xd6, 0xad, 0xcc, 0xef, 0xba, 0x95, 0x79, 0x3b, 0xe7, 0xf9, 0xd1, 0xce, 0x41, 0xd9, 0x71,
	0x45, 0x95, 0x4a, 0xe6, 0xb1, 0xc3, 0xda, 0x7b, 0x55, 0xf1, 0xb0, 0x55, 0x33, 0xaa, 0x85, 0x5c,
	0x96, 0x47, 0xd4, 0xf7, 0x6c, 0xe5, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x45, 0x64, 0xe4,
	0xb4, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ListChainletStack items.
	ListChainletStack(ctx context.Context, in *QueryListChainletStackRequest, opts ...grpc.CallOption) (*QueryListChainletStackResponse, error)
	// Queries a list of GetChainletStack items.
	GetChainletStack(ctx context.Context, in *QueryGetChainletStackRequest, opts ...grpc.CallOption) (*QueryGetChainletStackResponse, error)
	// Queries a list of ListChainlets items.
	ListChainlets(ctx context.Context, in *QueryListChainletsRequest, opts ...grpc.CallOption) (*QueryListChainletsResponse, error)
	// Queries a list of GetChainlet items.
	GetChainlet(ctx context.Context, in *QueryGetChainletRequest, opts ...grpc.CallOption) (*QueryGetChainletResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ssc.chainlet.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListChainletStack(ctx context.Context, in *QueryListChainletStackRequest, opts ...grpc.CallOption) (*QueryListChainletStackResponse, error) {
	out := new(QueryListChainletStackResponse)
	err := c.cc.Invoke(ctx, "/ssc.chainlet.Query/ListChainletStack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetChainletStack(ctx context.Context, in *QueryGetChainletStackRequest, opts ...grpc.CallOption) (*QueryGetChainletStackResponse, error) {
	out := new(QueryGetChainletStackResponse)
	err := c.cc.Invoke(ctx, "/ssc.chainlet.Query/GetChainletStack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListChainlets(ctx context.Context, in *QueryListChainletsRequest, opts ...grpc.CallOption) (*QueryListChainletsResponse, error) {
	out := new(QueryListChainletsResponse)
	err := c.cc.Invoke(ctx, "/ssc.chainlet.Query/ListChainlets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetChainlet(ctx context.Context, in *QueryGetChainletRequest, opts ...grpc.CallOption) (*QueryGetChainletResponse, error) {
	out := new(QueryGetChainletResponse)
	err := c.cc.Invoke(ctx, "/ssc.chainlet.Query/GetChainlet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ListChainletStack items.
	ListChainletStack(context.Context, *QueryListChainletStackRequest) (*QueryListChainletStackResponse, error)
	// Queries a list of GetChainletStack items.
	GetChainletStack(context.Context, *QueryGetChainletStackRequest) (*QueryGetChainletStackResponse, error)
	// Queries a list of ListChainlets items.
	ListChainlets(context.Context, *QueryListChainletsRequest) (*QueryListChainletsResponse, error)
	// Queries a list of GetChainlet items.
	GetChainlet(context.Context, *QueryGetChainletRequest) (*QueryGetChainletResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListChainletStack(ctx context.Context, req *QueryListChainletStackRequest) (*QueryListChainletStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChainletStack not implemented")
}
func (*UnimplementedQueryServer) GetChainletStack(ctx context.Context, req *QueryGetChainletStackRequest) (*QueryGetChainletStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainletStack not implemented")
}
func (*UnimplementedQueryServer) ListChainlets(ctx context.Context, req *QueryListChainletsRequest) (*QueryListChainletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChainlets not implemented")
}
func (*UnimplementedQueryServer) GetChainlet(ctx context.Context, req *QueryGetChainletRequest) (*QueryGetChainletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainlet not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssc.chainlet.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListChainletStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListChainletStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListChainletStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssc.chainlet.Query/ListChainletStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListChainletStack(ctx, req.(*QueryListChainletStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetChainletStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetChainletStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetChainletStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssc.chainlet.Query/GetChainletStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetChainletStack(ctx, req.(*QueryGetChainletStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListChainlets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListChainletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListChainlets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssc.chainlet.Query/ListChainlets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListChainlets(ctx, req.(*QueryListChainletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetChainlet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetChainletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetChainlet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ssc.chainlet.Query/GetChainlet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetChainlet(ctx, req.(*QueryGetChainletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ssc.chainlet.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListChainletStack",
			Handler:    _Query_ListChainletStack_Handler,
		},
		{
			MethodName: "GetChainletStack",
			Handler:    _Query_GetChainletStack_Handler,
		},
		{
			MethodName: "ListChainlets",
			Handler:    _Query_ListChainlets_Handler,
		},
		{
			MethodName: "GetChainlet",
			Handler:    _Query_GetChainlet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ssc/chainlet/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListChainletStackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListChainletStackRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListChainletStackRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListChainletStackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListChainletStackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListChainletStackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainletStacks) > 0 {
		for iNdEx := len(m.ChainletStacks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChainletStacks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetChainletStackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetChainletStackRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetChainletStackRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetChainletStackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetChainletStackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetChainletStackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ChainletStack.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListChainletsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListChainletsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListChainletsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListChainletsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListChainletsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListChainletsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Chainlets) > 0 {
		for iNdEx := len(m.Chainlets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chainlets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetChainletRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetChainletRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetChainletRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetChainletResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetChainletResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetChainletResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Chainlet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListChainletStackRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListChainletStackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ChainletStacks) > 0 {
		for _, e := range m.ChainletStacks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetChainletStackRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetChainletStackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ChainletStack.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListChainletsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListChainletsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Chainlets) > 0 {
		for _, e := range m.Chainlets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetChainletRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetChainletResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Chainlet.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListChainletStackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListChainletStackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListChainletStackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListChainletStackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListChainletStackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListChainletStackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainletStacks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainletStacks = append(m.ChainletStacks, &ChainletStack{})
			if err := m.ChainletStacks[len(m.ChainletStacks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetChainletStackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetChainletStackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetChainletStackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetChainletStackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetChainletStackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetChainletStackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainletStack", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ChainletStack.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListChainletsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListChainletsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListChainletsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListChainletsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListChainletsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListChainletsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chainlets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chainlets = append(m.Chainlets, &Chainlet{})
			if err := m.Chainlets[len(m.Chainlets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetChainletRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetChainletRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetChainletRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetChainletResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetChainletResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetChainletResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chainlet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Chainlet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
