name: Push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract tag name
        id: tag_name
        run: |
          TAG_REF=${GITHUB_REF#refs/tags/}
          FORMATTED_TAG=${TAG_REF#v}
          echo "FORMATTED_TAG=${FORMATTED_TAG}" >> $GITHUB_ENV
          echo "::set-output name=formatted_tag::${FORMATTED_TAG}"
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sagaxyz/ssc:${{ steps.tag_name.outputs.formatted_tag }}
