name: golangci-lint
on:
  push:
    branches:
      - '**'
permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/sagaxyz/*
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
          cache: true
      - run: go version
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 600s