name: ShellCheck

on: [push]

permissions:
  contents: read
jobs:
  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/sagaxyz/*
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2086,SC2015,SC2034,SC1090,SC2028,SC2209,SC2046,SC2218
